// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJAHkEkobTYYrYkQSvsK9rwM2_VrrbV4E',
    appId: '1:893114148393:web:56b6c1108c967d25cede38',
    messagingSenderId: '893114148393',
    projectId: 'smart-home-automation-724d1',
    authDomain: 'smart-home-automation-724d1.firebaseapp.com',
    databaseURL: 'https://smart-home-automation-724d1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-automation-724d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfp9L0InVvwXptcF4yRaTZCpAroro9ro4',
    appId: '1:893114148393:android:bb7e0c310ddcc1d9cede38',
    messagingSenderId: '893114148393',
    projectId: 'smart-home-automation-724d1',
    databaseURL: 'https://smart-home-automation-724d1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-automation-724d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFQCyzRiqz7Ifn15tjYvk5TUXFnxiE_eA',
    appId: '1:893114148393:ios:a8c796577ff316cccede38',
    messagingSenderId: '893114148393',
    projectId: 'smart-home-automation-724d1',
    databaseURL: 'https://smart-home-automation-724d1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-automation-724d1.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeAutomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFQCyzRiqz7Ifn15tjYvk5TUXFnxiE_eA',
    appId: '1:893114148393:ios:a8c796577ff316cccede38',
    messagingSenderId: '893114148393',
    projectId: 'smart-home-automation-724d1',
    databaseURL: 'https://smart-home-automation-724d1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-automation-724d1.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeAutomation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJAHkEkobTYYrYkQSvsK9rwM2_VrrbV4E',
    appId: '1:893114148393:web:931cc6bc98c1f938cede38',
    messagingSenderId: '893114148393',
    projectId: 'smart-home-automation-724d1',
    authDomain: 'smart-home-automation-724d1.firebaseapp.com',
    databaseURL: 'https://smart-home-automation-724d1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-automation-724d1.firebasestorage.app',
  );

}