name: smart_home_automation
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.1+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_database: ^11.1.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.1
  gap: ^3.0.1
  email_validator: ^3.0.0
  get: ^4.6.6
  toastification: ^2.3.0
  fluentui_system_icons: ^1.1.263
  icons_launcher: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^5.5.0
  clipboard: ^0.1.3
  flutter_code_editor: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/code/main.cpp

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
icons_launcher:
  image_path: "assets/logo.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true